### PR TITLE
DDF-626 Added ability to edit workspace names.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by bradh** [comment]
I tried this locally, and I think the change might need to be more extensive. 

The current "edit" functionality only allows you to delete workspaces. However with this change, there is now editing of labels / names. Good so far - its a good feature. The problem is what the Edit/Done toggle at the top right corner shows. It conceptually shows the mode you aren't in - it shows what you can do.  So if we're able to Edit, it shows Done.

However there is a case where it gets out of sequence. If you go to edit, make the change (but don't select Done), then go back to Search then back to Workspace, we're showing Done but we're not in edit mode.

I can see this as a separate issue (since it probably occurs in the current code, its just more obvious with this change). Just need to track the issue.

**Comment by mjmeno** [comment]
Thanks @bradh .  @mplachec  and @stustison, how extensive is a fix for the issue Brad points out?

**Comment by stustison** [comment]
I don't think it would be too difficult to fix, but we probably need a ticket for it.

**Comment by bradh** [comment]
I created a ticket at DDF-637 for that issue, and look forward to this being merged.

**Comment by shaundmorris** [comment]
@bradh thanks for creating the ticket.

**Pull request merged**
