### PR TITLE
DDF-1188: Removed unnecessary dependency that was causing an OWASP vulnerability in standard UI.

### PR DESCRIPTION
**Pull request by lessarderic**
[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-ui/75)

### CODE REVIEW

**Comment by lessarderic** [comment]
@shaun, @pklinef, @ricklarsen: Please review.

**Comment by ricklarsen** [comment]
+1 / built and tested.

**Comment by shaundmorris** [comment]
Interesting. So is ascii-doc 1.5.2 causing a vulnerability, does it exist elsewhere?

**Comment by lessarderic** [comment]
Yes, but not as a dependency, only as a plug-in. There really isn't any reason to have that in the dependency section of the pom file.

**Comment by shaundmorris** [comment]
:+1: for me. Just was curious about other locations in the code base

**Comment by shaundmorris** [comment]
@pklinef any thoughts here?

**Comment by lessarderic** [comment]
@phil: Please approve when you have a minute so we can merge that change in and get this building again in Jenkins.

**Pull request merged**
