### PR TITLE
DDF-549 Bower installs offline

### PR DESCRIPTION
**Pull request by harrison-t-lm**
This change enables grunt to first try to install bower offline, then if a package isn't in cache, it installs online. 
This is instead of using Artifactory as a repository

### CODE REVIEW

**Comment by bradh** [comment]
I admit to knowing little about grunt, but it isn't clear how this pull request relates to the original DDF-549 problem description (which looks like a spike to compare Artifactory vs Nexus). Maybe it just needs a bit of background prose in the pull request description?

**Comment by mrmateo** [comment]
@harrison-t-lm  can you respond to @bradh ? I'm guessing that artifactory didn't work out and so you tried to find another method that allows builds to work without needing access to github?

**Comment by harrison-t-lm** [comment]
I updated the description and title after receiving that comment. but yea, that's what happened. this ended up to be the simplest solution

**Comment by shaundmorris** [comment]
@harrison-t-lm  I also changed the ticket summary for DDF-549, you can double check me there as well.

**Pull request merged**
