### PR TITLE
DDF-1174 Adding jacoco config to DDF-UI

### PR DESCRIPTION
**Pull request by andrewkfiedler**
The top pom defers to the DDF-Parent configuration, but the rest of the poms have custom configurations for the minimum code coverage required (determined by an initial run with jacoco, with a subtraction of 5 percent to give some room).

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-ui/65)

### CODE REVIEW

**Comment by shaundmorris** [comment]
<sup>**[search-ui/search-geonames/pom.xml, line 1 [r1]](https://reviewable.io:443/reviews/codice/ddf-ui/65#-JnwxpS4lUPlFTbVp11n)** ([raw file](https://github.com/codice/ddf-ui/blob/1641df65f7e395244d9cd584513c7a49c52dd587/search-ui/search-geonames/pom.xml#L1)):</sup>
Is 'standalone="no"?' a default setting that caused it to be added to the pom files or is there a guideline you are following for adding it to each pom file?

---

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-ui/65)

**Comment by shaundmorris** [comment]
Reviewed files:
- docs/pom.xml @ r1
- pom.xml @ r1
- search-ui/search-endpoint/pom.xml @ r1
- search-ui/search-geocoder/pom.xml @ r1
- search-ui/search-geonames/pom.xml @ r1
- search-ui/search-htmltransformer/pom.xml @ r1
- search-ui/search-proxy/pom.xml @ r1
- search-ui/search-redirect/pom.xml @ r1
- search-ui/search-ui-app/pom.xml @ r1
- search-ui/simple/pom.xml @ r1
- search-ui/standard/pom.xml @ r1

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-ui/65)

**Comment by lessarderic** [comment]
<sup>**[docs/pom.xml, line 44 [r1]](https://reviewable.io:443/reviews/codice/ddf-ui/65#-Jnx3u25vdOKnyEUvWXx)** ([raw file](https://github.com/codice/ddf-ui/blob/1641df65f7e395244d9cd584513c7a49c52dd587/docs/pom.xml#L44)):</sup>
This can be removed since it uses the default %.

---

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-ui/65)

**Comment by shaundmorris** [comment]
<sup>**[docs/pom.xml, line 47 [r1]](https://reviewable.io:443/reviews/codice/ddf-ui/65#-Jnx4-qNvOz7VDyHrZdt)** ([raw file](https://github.com/codice/ddf-ui/blob/1641df65f7e395244d9cd584513c7a49c52dd587/docs/pom.xml#L47)):</sup>
Believe you could just use Plugin Management here and not include anything beyond the groupId and artifactId. since the limits are the same as ddf-parent, but we need that merged in first.

---

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-ui/65)

**Comment by lessarderic** [comment]
<sup>**[search-ui/search-proxy/pom.xml, line 90 [r1]](https://reviewable.io:443/reviews/codice/ddf-ui/65#-Jnx4cpwv9g7miaxrvCy)** ([raw file](https://github.com/codice/ddf-ui/blob/1641df65f7e395244d9cd584513c7a49c52dd587/search-ui/search-proxy/pom.xml#L90)):</sup>
Uses defaults. Remove.

---

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-ui/65)

**Comment by andrewkfiedler** [comment]
<sup>**[search-ui/search-geonames/pom.xml, line 1 [r1]](https://reviewable.io:443/reviews/codice/ddf-ui/65#-JnwxpS4lUPlFTbVp11n)** ([raw file](https://github.com/codice/ddf-ui/blob/1641df65f7e395244d9cd584513c7a49c52dd587/search-ui/search-geonames/pom.xml#L1)):</sup>
It's a default setting that we've added to the pom files.  Eric might know more about why we chose to have it set to no.  Do we have a DTD (Document Type Definition) for any of the xml files?  If we don't, than this setting won't do anything.  

---

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-ui/65)

**Comment by shaundmorris** [comment]
Reviewed files:
- docs/pom.xml @ r2
- pom.xml @ r2
- search-ui/pom.xml @ r2
- search-ui/search-endpoint/pom.xml @ r2
- search-ui/search-geocoder/pom.xml @ r2
- search-ui/search-geonames/pom.xml @ r2
- search-ui/search-htmltransformer/pom.xml @ r2
- search-ui/search-proxy/pom.xml @ r2
- search-ui/search-redirect/pom.xml @ r2
- search-ui/search-ui-app/pom.xml @ r2
- search-ui/simple/pom.xml @ r2
- search-ui/standard/pom.xml @ r2

---

<sup>**[search-ui/search-geonames/pom.xml, line 1 [r1]](https://reviewable.io:443/reviews/codice/ddf-ui/65#-JnwxpS4lUPlFTbVp11n)** ([raw file](https://github.com/codice/ddf-ui/blob/1641df65f7e395244d9cd584513c7a49c52dd587/search-ui/search-geonames/pom.xml#L1)):</sup>
+1, don't think we have DTD's so it shouldn't be necessary, but don't think it does any harm either.

---

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-ui/65)

**Comment by lessarderic** [comment]
<sup>**[search-ui/search-geonames/pom.xml, line 1 [r1]](https://reviewable.io:443/reviews/codice/ddf-ui/65#-JnwxpS4lUPlFTbVp11n)** ([raw file](https://github.com/codice/ddf-ui/blob/1641df65f7e395244d9cd584513c7a49c52dd587/search-ui/search-geonames/pom.xml#L1)):</sup>
I didn't really set that attribute on purpose. The class we use to serialize the XML from the DOM in our Groovy script adds this by default. We can take it out but would need to update the script and most of the pom files.

---

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-ui/65)

**Comment by shaundmorris** [comment]
Must have missed something on the merge, but this should be merged in

**Pull request closed without merging**
