### PR TITLE
DDF-1156 - cleaned up searchPage.css to display all tips to the right of...

### PR DESCRIPTION
**Pull request by kcwire**
... the heading instead of below

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-ui/60)

### CODE REVIEW

**Comment by kcwire** [comment]
See the ticket for where the tips were before - now they are to the right.
screen shot 2015-04-07 at 5 10 50 pm

**Comment by stustison** [comment]
+1

**Comment by shaundmorris** [comment]
@kcwire looks like this can't be auto-merged anymore. LGTM other than that :-)

**Comment by kcwire** [comment]
This may be OBE will double check.

**Comment by andrewkfiedler** [comment]
I like the idea of the change, but we could just take advantage of how the html already behaves and do something like this:

```
<h6>Keywords <i class="fa fa-question-circle" data-toggle="keyword-popover"></i></h6>
```

Then you can get rid of the css concerning the display properties of the tags.

**Comment by jlcsmith** [comment]
@kcwire - it looks like the tooltip formatting was fixed by other commits.  Can this be closed or is there something left to be merged still?

**Pull request closed without merging**
