### PR TITLE
DDF-1055 

### PR DESCRIPTION
**Pull request by ghost**
Geo features drawn on map (2d and 3d) can be cleared after a search.

### CODE REVIEW

**Comment by shaundmorris** [comment]
I verified this fix works on the 2D and 3D maps. @mplachec the only time I couldn't get rid of the features on the map is when I tried to complete the polygon prior to 3 points, so not sure if that is a separate issue. @pklinef or @stustison any ideas on that?

**Comment by stustison** [comment]
Yeah that is a separate issue. I believe @mplachec wrote up another ticket for it yesterday.

**Comment by shaundmorris** [comment]
Okay I didn't see a ticket so I'll wait on that until I hear from @mplachec on it, just want to make sure we capture it. If there is nothing else @stustison I believe we can merge this in.

**Comment by ghost** [comment]
@shaundmorris There are two issues with the polygons (one on 3d and one on 2d) that I wrote up tickets.

https://tools.codice.org/jira/browse/DDF-1062
https://tools.codice.org/jira/browse/DDF-1061

**Pull request merged**
