### PR TITLE
Ddf 1238 Fix for stopping Search UI

### PR DESCRIPTION
**Pull request by clockard**
@stustison 
@pklinef

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-ui/82)

### CODE REVIEW

**Comment by shaundmorris** [comment]
Review status: all files reviewed, all discussions resolved, some commit checks broke.
Reviewed files:
- search-ui/pom.xml @ r1
- search-ui/search-proxy/pom.xml @ r1
- search-ui/search-proxy/src/main/resources/OSGI-INF/blueprint/blueprint.xml @ r1
- search-ui/search-ui-app/src/main/resources/features.xml @ r1
- search-ui/standard/pom.xml @ r1
- search-ui/standard/src/main/java/org/codice/ddf/ui/searchui/standard/properties/ConfigurationStore.java @ r1
- search-ui/standard/src/main/resources/OSGI-INF/blueprint/blueprint.xml @ r1
- search-ui/standard/src/test/java/org/codice/ddf/ui/searchui/standard/properties/ConfigurationStoreTest.java @ r1

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-ui/82)

**Comment by pklinef** [comment]
:+1:

---

Review status: all files reviewed, all discussions resolved, some commit checks broke.
Reviewed files:
- search-ui/pom.xml @ r1
- search-ui/search-proxy/pom.xml @ r1
- search-ui/search-proxy/src/main/resources/OSGI-INF/blueprint/blueprint.xml @ r1
- search-ui/search-ui-app/src/main/resources/features.xml @ r1
- search-ui/standard/pom.xml @ r1
- search-ui/standard/src/main/java/org/codice/ddf/ui/searchui/standard/properties/ConfigurationStore.java @ r1
- search-ui/standard/src/main/resources/OSGI-INF/blueprint/blueprint.xml @ r1
- search-ui/standard/src/test/java/org/codice/ddf/ui/searchui/standard/properties/ConfigurationStoreTest.java @ r1

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-ui/82)

**Comment by stustison** [comment]
:+1:

**Comment by shaundmorris** [comment]
This is good to go the build failures travis is showing are related to the ddf-parent tag having the SNAPSHOT dependency of ddf.support.checkstyle

**Comment by clockard** [comment]
Did anyone pull the branch and test this? I forgot to get someone to be the hero for this PR.

**Comment by shaundmorris** [comment]
I just did a full build and it passed for me because I have the checkstyle SNAPSHOT version locally. The issue was addressed by commits from @kcwire and @stustison

**Pull request merged**
