### PR TITLE
DDF-1183: Update to have this module inherit frontend-maven-plugin versions from the parent POM file.

### PR DESCRIPTION
**Pull request by ghost**
[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-ui/74)

### CODE REVIEW

**Comment by ghost** [comment]
@oconnormi, @jckilmer, @lessarderic

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-ui/74)

**Comment by lessarderic** [comment]
Reviewed files:
- search-ui/standard/pom.xml @ r1

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-ui/74)

**Comment by jckilmer** [comment]
Reviewed files:
- search-ui/standard/pom.xml @ r1

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-ui/74)

**Comment by ghost** [comment]
@phil, @shaun

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-ui/74)

**Comment by shaundmorris** [comment]
Reviewed files:
- search-ui/standard/pom.xml @ r1

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-ui/74)

**Pull request merged**
