### PR TITLE
DDF-1280: Fixing issue where query data wouldn't update correctly, added test

### PR DESCRIPTION
**Pull request by andrewkfiedler**
- Query.js:  Updated "buildSearchData" method to correctly reset filters.
- query2.json: New test data.  It's a query response with 0 hits.
- test.js: Added a ternary so that it's possible for query2.json to be returned.
- search.js:  Updated some tests to use innerHTML instead of innerText (saucelabs was complaining).
- workspaces.js:  Added "should return different results after editing search keyword" test.

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-ui/89)

### CODE REVIEW

**Comment by andrewkfiedler** [comment]
@brianfelix as hero, @pklinef

**Comment by stustison** [comment]
:+1:

**Comment by pklinef** [comment]
Did you get a chance to run this against Sauce Labs?

**Comment by pklinef** [comment]
:+1:

**Comment by brianfelix** [comment]
built and tested :+1:

**Comment by andrewkfiedler** [comment]
Yeah, I ran it against sauce labs quite a few times. It actually started failing on some older tests, so I had to update them.  For some reason it didn't like innerText, so I changed it to innerHTML.

**Pull request merged**
