### PR TITLE
DDF-1240: Point-radius search after polygon search fixed

### PR DESCRIPTION
**Pull request by brianfelix**
[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-ui/83)

### CODE REVIEW

**Comment by brianfelix** [comment]
@stustison @andrewkfiedler please hero

**Comment by andrewkfiedler** [comment]
@andrew-fiedler

**Comment by brianfelix** [comment]
I updated the comment above the change to be easier to understand. Let me know if it is not clear

**Comment by andrewkfiedler** [comment]
:+1: built and tested

**Comment by brianfelix** [comment]
@pklinef

**Comment by pklinef** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

<sup>**[search-ui/standard/src/main/webapp/js/model/Query.js, line 203 [r2]](https://reviewable.io:443/reviews/codice/ddf-ui/83#-Jrx_XS-2LjuszkyDpgT)** ([raw file](https://github.com/codice/ddf-ui/blob/7ab7a3a85bbd69892c4b1d61be7bcf9eab21985b/search-ui/standard/src/main/webapp/js/model/Query.js#L203)):</sup>
This makes it look like if you have values set for point radius, bounding box, and polygon, that the query will pick the values in that order instead of what is actually being displayed in the UI.  I wonder if we should instead extend the model to set which values are being displayed and use that to determine what to send as the actual query.  Another option would be to clear the values for sections not being shown when the search button is clicked.  Then the model will only contain values that are being displayed.  The first option would let you keep other values available if you go back after search but the second option would probably be easier to implement.  Both of those options should make the UI more intuitive and predictable.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-ui/83)

**Pull request closed without merging**
