### PR TITLE
DDF-1297: Source list dropdown no longer expands off the screen

### PR DESCRIPTION
**Pull request by jrnorth**
[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-ui/95)

### CODE REVIEW

**Comment by jrnorth** [comment]
@kcwire
@millerw8 
@wmcnalli
@jlcsmith
@beyelerb
@emanns95
@jrnorth
@coyotesqrl

**Comment by duckbyte** [comment]
+1

**Comment by jaymcnallie** [comment]
+1

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-ui/95)

**Comment by coyotesqrl** [comment]
:+1:

**Pull request merged**
