### PR TITLE
DDF-1270: enabled compilation of docs into single html/pdf file.

### PR DESCRIPTION
**Pull request by ricklarsen**
[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-ui/92)

### CODE REVIEW

**Comment by ricklarsen** [comment]
@smithjosh @shaundmorris @pklinef

**Comment by SmithJosh** [comment]
Verified that build succeeds, all tests pass, and the maven-assembly-plugin exclusions work correctly.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-ui/92)

**Comment by shaundmorris** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[docs/src/main/resources/ManContents.adoc, line 1 [r1]](https://reviewable.io:443/reviews/codice/ddf-ui/92#-JsgXY3mEO2SNA4JjOdv)** ([raw file](https://github.com/codice/ddf-ui/blob/305758835f4f0eb98b3f4631931acb62c85b700c/docs/src/main/resources/ManContents.adoc#L1)):</sup>
Not a big deal to me but I'm assuming the "Man" in "ManContents" was for Managing? 

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-ui/92)

**Comment by ricklarsen** [comment]
<sup>**[docs/src/main/resources/ManContents.adoc, line 1 [r1]](https://reviewable.io:443/reviews/codice/ddf-ui/92#-JsgXY3mEO2SNA4JjOdv)** ([raw file](https://github.com/codice/ddf-ui/blob/305758835f4f0eb98b3f4631931acb62c85b700c/docs/src/main/resources/ManContents.adoc#L1)):</sup>
That's correct. 

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-ui/92)

**Comment by pklinef** [comment]
:+1:

**Comment by clockard** [comment]
Reviewed 7 of 9 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-ui/92)

**Comment by clockard** [comment]
:+1:

**Comment by ricklarsen** [comment]
Repo deprecated. Changes moved into ddf-catalog/ui

**Pull request closed without merging**
