### PR TITLE
DDF-877 - Fixed an internal backbone-association's error caused by dot notation in json attribute names

### PR DESCRIPTION
**Pull request by McLucas**
-json output containing attribute names with "." in their names were causing issues with the "_getAttr" method in Backbone.Associations.  When dot notation is used with a Model.set() or a Model.get(), it tries to do sub-object path based on the dot notation used (which is not what we want)
-Changing the Backbone.Associations.SEPARATOR from "." (the default) to "~" fixes the issue.  Sub-Selecting can still be done, but you will need to use the ~ character instead.
-The subObject pathing can be explained at http://dhruvaray.github.io/backbone-associations/specify-associations.html#sa-getsetop

### CODE REVIEW

**Comment by McLucas** [comment]
This addresses the Search Spinner freeze bug.  Results were coming back, but there was an uncaught/silent backbone.associations exception caused by "."/dot notation in the JSON attribute names.

Example of dot notation:
{
  "ddms20.metacard": {
    "ddms-geospatial.identifier.name": "STRING",
    "ddms-format.media": "STRING"
  }
}

**Comment by shaundmorris** [comment]
@pklinef  did you have any thoughts on this PR? If it addresses the issue I would love to merge in.

**Comment by pklinef** [comment]
"~" seems like an odd pick but it looks good to me.

**Comment by McLucas** [comment]
@pklinef  I'd be open to change to whatever you guys would like.  Maybe one of these: ">" , "->" , ":" , ">>".  As long as its not any character used in our json attribute naming.

**Comment by pklinef** [comment]
I already merged.  It is not a big deal currently since we do not use that feature of Associations yet.

If Associations supports using two characters for the separator, I could see "->" or ">>" since those would be very unlikely to be used.  I will leave it up to you if you want to change it now or not.

**Pull request merged**
